generator:
  class: sfDoctrineGenerator
  param:
    model_class:           sfGuardPermission
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sf_guard_permission
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title:   Permissions management
        batch_actions: {}
        max_per_page: 20
      filter:
        class: false
      form:    ~
      edit:    ~
      new:     ~
